---
title: "sts_deck_ar"
author: "triballs"
date: "March 11, 2019"
output: html_document
---

# An attempt in running association rules on deck sets in Slay the Spire.

## Extracting deck lists from raw rundata files.
```{r}
rm(list = ls())
library(rjson)

path <- paste(getwd(),"/rundata/user1/IRONCLAD", sep="") # directory path for the .run files being read
temp <- list.files(path, pattern="*.run", full.names=TRUE)  # store the full filepaths of all the .run files as a chr vector
deck_list <- vector(mode = "list", length = length(temp))
for(i in seq(temp)){
  d <- fromJSON(file = temp[i])
  deck_list[[i]] <- d$master_deck
}

setwd("C:/myapps/sts_ar")
filename <- "user1.ironchad.csv"
cat("", file = filename, append = FALSE)
for(entry in deck_list){
  cat(entry, file = filename, sep = ",", append = TRUE)
  cat("\n", file = filename, append = TRUE)
}
```


## read the deck_list from exported .csv
```{r}
u1_chad <- read.transactions("./user1.ironchad.csv", sep=",")
summary(u1_chad)
inspect(u1_chad[1:5])

```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
